apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-demo
  template:
    metadata:
      labels:
        app: cicd-demo
    spec:
      containers:
      - name: nginx
        image: ghcr.io/jeffyang123/my-cicd-demo:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-demo-svc
spec:
  type: NodePort
  selector:
    app: cicd-demo
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
